---
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  vault-test
  labels:
    app:  vault-test
spec:
  selector:
    matchLabels:
      app: vault-test
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  vault-test
    spec:
      containers:
      - name: vault-test
        image: registry.digitalocean.com/fakku-demo/vault-test:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: VAULT_ADDR
          value: http://helm-vault:8200
        - name: VAULT_TOKEN
          value: root
        - name: MYSQL_VAULT_SECRET
          value: secret/db/mysql-fakku-beta
      restartPolicy: Always

