namespace: utils

resources:
  - crds/ingressroute.yaml
  - crds/ingressroutetcp.yaml
  - crds/ingressrouteudp.yaml
  - crds/middlewares.yaml
  - crds/middlewarestcp.yaml
  - crds/serverstransports.yaml
  - crds/tlsoptions.yaml
  - crds/tlsstores.yaml
  - crds/traefikservices.yaml
  - templates/rbac/clusterrole.yaml
  - templates/rbac/clusterrolebinding.yaml
  - templates/rbac/serviceaccount.yaml
  - templates/dashboard-hook-ingressroute.yaml
  - templates/deployment.yaml
  - templates/hpa.yaml
  - templates/poddisruptionbudget.yaml
  - templates/service.yaml

images:
  - name: traefik
    newTag: v2.6.1