namespace: utils

helmChartInflationGenerator:
  - chartName: traefik
    chartRepoUrl: https://helm.traefik.io/traefik
    chartVersion: "10.14.2"
    releaseName: traefik
    values: helm.values.yaml
    extraArgs:
      - --include-crds

images:
  - name: traefik
    newTag: v2.6.1