apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: argo
  source:
    path: k8s/kustomize/bases/argo-events
    repoURL: git@github.com:reynn/fakku-cloud-resources.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
