apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argo-cd
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.dev.tenk.ai`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
          scheme: http
        - name: argocd-server
          port: 443
          scheme: https
    - kind: Rule
      match: Host(`argocd.dev.tenk.ai`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 443
          scheme: h2c
  tls:
    certResolver: lehttp