apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argo-workflows
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`workflows.dev.tenk.ai`)
      priority: 10
      services:
        - name: argo-server
          port: 2746
